In [37]:
import numpy as np
import math

In [38]:
# SOME HARD CODED VALUES FOR ROBOT PARAMETERS
l1 = 0.2
l2 = 0.3
r1 = 0.2
r2 = 0.25
r3 = 0.3
theta1 = 1.53
theta2 = 1.51
theta3 = 1.4
phi = 1.3


In [45]:
# MAKE A DH PARAMETER TABLE
# d, alpha, r, theta
dh_parameters = np.array(
  [
   [0, 0, 0, phi],
   [r1, 1.57, 0, 0],
   [0, 0, r1 + l1 + r2, theta1],
   [0, 0, r2 + l2 + r3, theta2],
   [0, 0, r3, theta3]
  ] 
)
print(dh_parameters)


[[0.   0.   0.   1.3 ]
 [0.2  1.57 0.   0.  ]
 [0.   0.   0.65 1.53]
 [0.   0.   0.85 1.51]
 [0.   0.   0.3  1.4 ]]


In [46]:

# MAKE A DH MATRIX FOR THE ROBOT

# USING THE PARAMETERS 
dh_matrix = np.diag(np.ones((4)))
print(dh_matrix)  
for row in dh_parameters:
  trans_z = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, row[0]],
    [0, 0, 0, 1]
  ])
  dh_matrix = np.matmul(trans_z, dh_matrix)
  rot_z = np.array([
    [math.cos(row[3]), -1 * math.sin(row[3]), 0, 0],
    [math.sin(row[3]), math.cos(row[3]), 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0 ,1]
  ])
  dh_matrix =  np.matmul(rot_z, dh_matrix)
  trans_x = np.array([
    [1, 0, 0, row[2]],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
  ])
  dh_matrix = np.matmul(trans_x, dh_matrix)
  rot_x = np.array([
    [1, 0, 0, 0],
    [0, math.cos(row[1]), -1 * math.sin(row[1]), 0],
    [0, math.sin(row[1]), math.cos(row[1]), 0],
    [0, 0, 0, 1]
  ])
  dh_matrix = np.matmul(rot_x, dh_matrix)
  
print(dh_matrix) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[-7.12270227e-02  2.59434211e-01 -9.63130625e-01 -3.80800400e-01]
 [-2.57842827e-01  9.27975383e-01  2.69033018e-01  1.04063204e+00]
 [ 9.63557880e-01  2.67498744e-01  7.96326711e-04  1.59265342e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [ ]:
# SET END POSITION

In [ ]:

# ALGORITHM

# CALCULATE THE JACOBIAN

# CALCULATE THE JACOBIAN TRANSPOSE

# 